sudo: required

services:
  - docker

env:
  matrix :
    - env:
      NODE_PATCH_VERSION: '7.10.0'
      NODE_MINOR_VERSION: '7.10'
      NODE_MAJOR_VERSION: '7'
      LATEST: 'latest'
    - env:
      NODE_PATCH_VERSION: '6.10.3'
      NODE_MINOR_VERSION: '6.10'
      NODE_MAJOR_VERSION: '6'
    - env:
      NODE_PATCH_VERSION: '4.8.3'
      NODE_MINOR_VERSION: '4.8'
      NODE_MAJOR_VERSION: '4'

install:
  - docker build -t "escaleno/node-krb5:$NODE_PATCH_VERSION" "$NODE_PATCH_VERSION"
  - docker build -t "escaleno/node-krb5:$NODE_PATCH_VERSION-onbuild" "$NODE_PATCH_VERSION/onbuild"

script:
  - docker run --rm "escaleno/node-krb5:$NODE_PATCH_VERSION" node --version

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker tag "escaleno/node-krb5:$NODE_PATCH_VERSION" "escaleno/node-krb5:$NODE_MINOR_VERSION"
  - docker tag "escaleno/node-krb5:$NODE_PATCH_VERSION" "escaleno/node-krb5:$NODE_MAJOR_VERSION"
  - docker tag "escaleno/node-krb5:$NODE_PATCH_VERSION-onbuild" "escaleno/node-krb5:$NODE_MINOR_VERSION-onbuild"
  - docker tag "escaleno/node-krb5:$NODE_PATCH_VERSION-onbuild" "escaleno/node-krb5:$NODE_MAJOR_VERSION-onbuild"
  - docker push "escaleno/node-krb5:$NODE_PATCH_VERSION"
  - docker push "escaleno/node-krb5:$NODE_MINOR_VERSION"
  - docker push "escaleno/node-krb5:$NODE_MAJOR_VERSION"
  - docker push "escaleno/node-krb5:$NODE_PATCH_VERSION-onbuild"
  - docker push "escaleno/node-krb5:$NODE_MINOR_VERSION-onbuild"
  - docker push "escaleno/node-krb5:$NODE_MAJOR_VERSION-onbuild"
  - if [ "$LATEST" == "latest" ]; then
    docker tag "escaleno/node-krb5:$NODE_PATCH_VERSION" "escaleno/node-krb5:latest";
    docker tag "escaleno/node-krb5:$NODE_PATCH_VERSION-onbuild" "escaleno/node-krb5:onbuild";
    docker push "escaleno/node-krb5:latest";
    docker push "escaleno/node-krb5:onbuild";
    fi
